kafka:
  producer:
    bootstrap-servers: localhost:9092
    registry-url: http://localhost:8081
    topic:
      orders: orders
#spring:
#  cloud:
#    stream:
#      kafka:
#        streams:
#          bindings:
#            ordersout:
#              producer:
#                key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                value-serde: io.confluent.kafka.serializers.KafkaAvroSerializer

spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: io.confluent.kafka.serializers.KafkaAvroSerializer      
      bindings:
        orderout:
          destination: orders