dependencies:
  - name: order
    version: 0.0.1
    repository: file://../order
  - name: inventory
    version: 0.0.1
    repository: file://../inventory
  - name: credit
    version: 0.0.1
    repository: file://../credit
  - name: queryorder
    version: 0.0.1
    repository: file://../queryorder
  - name: analytics
    version: 0.0.1
    repository: file://../analytics